<script setup>
import { TASK_PRIORITIES, TASK_STATUSES, TASK_TYPES } from '#shared/schemas/tasks'
import { focusRouteForTask, plannerRouteForTask } from '#shared/tasks/task-routes'
import { recordedFocusSecondsForTask } from '#shared/tasks/task-intelligence'
import { createFocusStorage } from '~/utils/focus-storage.client'
import '~/assets/css/tasks.css'

definePageMeta({ layout: 'app', middleware: ['auth', 'onboarded'] })
useSeoMeta({ title: 'Tasks · Northstar', description: 'Turn academic requirements into concrete study actions.' })
const route = useRoute()
const { user } = useCurrentSession()
const { state: moduleState, load: loadModules } = useModules()
const { records: assessmentRecords, load: loadAssessments } = useAssessments()
const { tasks, loading, saving, error, fieldErrors, load, create, update, complete, remove, createSubtask } = useTasks()
const view = ref(['TODAY','OVERDUE','UPCOMING','BACKLOG','COMPLETED','ALL'].includes(String(route.query.view)) ? String(route.query.view) : 'TODAY')
const filters = reactive({ moduleEnrolmentId: String(route.query.moduleEnrolmentId || ''), type: '', priority: '', status: '' })
const editorOpen = ref(false)
const editingId = ref(null)
const localSessions = ref([])
const form = reactive({ title: '', moduleEnrolmentId: '', type: 'STUDY', priority: 'MEDIUM', status: 'BACKLOG', dueAt: '', timingNote: '', estimatedMinutes: null, actualMinutes: null, assessmentId: '', recurringCourseworkId: '', recurringCourseworkOccurrenceId: '', assessmentMilestoneId: '', description: '' })
const views = ['TODAY','OVERDUE','UPCOMING','BACKLOG','COMPLETED','ALL']
const label = value => value?.replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, letter => letter.toUpperCase())
const modules = computed(() => moduleState.value?.modules || moduleState.value?.items || [])
const assessments = computed(() => assessmentRecords.value[form.moduleEnrolmentId]?.assessments || [])
const query = computed(() => Object.fromEntries(Object.entries({ view: view.value, ...filters }).filter(([, value]) => value)))
const localMinutes = task => Math.round(recordedFocusSecondsForTask(localSessions.value, task.id) / 60)
const inputDate = value => value ? new Date(new Date(value).getTime() - new Date(value).getTimezoneOffset() * 60000).toISOString().slice(0, 16) : ''
function reset(prefill = {}) { editingId.value = null; Object.assign(form, { title: '', moduleEnrolmentId: '', type: 'STUDY', priority: 'MEDIUM', status: 'BACKLOG', dueAt: '', timingNote: '', estimatedMinutes: null, actualMinutes: null, assessmentId: '', recurringCourseworkId: '', recurringCourseworkOccurrenceId: '', assessmentMilestoneId: '', description: '', ...prefill }) }
function openCreate(prefill = {}) { reset(prefill); editorOpen.value = true }
function openEdit(task) { editingId.value = task.id; Object.assign(form, { title: task.title, moduleEnrolmentId: task.moduleEnrolmentId || '', type: task.type, priority: task.priority, status: task.status, dueAt: inputDate(task.dueAt), timingNote: task.timingNote || '', estimatedMinutes: task.estimatedMinutes, actualMinutes: task.actualMinutes, assessmentId: task.assessmentId || '', recurringCourseworkId: task.recurringCourseworkId || '', recurringCourseworkOccurrenceId: task.recurringCourseworkOccurrenceId || '', assessmentMilestoneId: task.assessmentMilestoneId || '', description: task.description || '' }); editorOpen.value = true }
function payload() { const empty = value => editingId.value ? value || null : value || undefined; return { ...form, moduleEnrolmentId: empty(form.moduleEnrolmentId), assessmentId: empty(form.assessmentId), recurringCourseworkId: empty(form.recurringCourseworkId), recurringCourseworkOccurrenceId: empty(form.recurringCourseworkOccurrenceId), assessmentMilestoneId: empty(form.assessmentMilestoneId), dueAt: form.dueAt ? new Date(form.dueAt).toISOString() : editingId.value ? null : undefined, timingNote: empty(form.timingNote), description: empty(form.description), estimatedMinutes: form.estimatedMinutes === '' ? editingId.value ? null : undefined : form.estimatedMinutes, actualMinutes: form.actualMinutes === '' ? editingId.value ? null : undefined : form.actualMinutes } }
async function save() { const result = editingId.value ? await update(editingId.value, payload()) : await create(payload()); if (result) { editorOpen.value = false; await refresh() } }
async function refresh() { await load(query.value) }
async function start(task) { await update(task.id, { status: 'IN_PROGRESS' }) }
async function reschedule(task) { const value = window.prompt('New due date and time (YYYY-MM-DDTHH:mm)', inputDate(task.dueAt)); if (value) await update(task.id, { dueAt: new Date(value).toISOString(), status: 'PLANNED' }) }
async function split(task) { const title = window.prompt('Subtask title'); if (title?.trim()) await createSubtask(task.id, { title, type: task.type, priority: task.priority, status: 'BACKLOG' }) }
async function cancel(task) { await update(task.id, { status: 'CANCELLED' }) }
async function destroy(task) { if (window.confirm(`Delete “${task.title}” and its subtasks?`)) await remove(task.id) }
async function toggleComplete(task) { await complete(task.id, task.status !== 'COMPLETED'); await refresh() }
watch(() => form.moduleEnrolmentId, value => { if (value) void loadAssessments(value) })
watch(query, refresh, { deep: true })
onMounted(async () => { await loadModules(); await refresh(); if (user.value?.id) localSessions.value = createFocusStorage(window.localStorage).load(user.value.id).sessions; if (route.query.create) openCreate({ title: String(route.query.title || ''), moduleEnrolmentId: String(route.query.moduleEnrolmentId || ''), assessmentId: String(route.query.assessmentId || ''), recurringCourseworkId: String(route.query.recurringCourseworkId || ''), recurringCourseworkOccurrenceId: String(route.query.recurringCourseworkOccurrenceId || ''), assessmentMilestoneId: String(route.query.assessmentMilestoneId || ''), timingNote: String(route.query.timingNote || ''), dueAt: route.query.dueAt ? inputDate(route.query.dueAt) : '', estimatedMinutes: route.query.estimatedMinutes ? Number(route.query.estimatedMinutes) : null }) })
</script>

<template><main class="app-page v2-page tasks-page">
  <header class="v2-page-heading"><div><p>Tasks</p><h1>Academic execution queue</h1></div><UButton icon="i-lucide-plus" @click="openCreate()">Add task</UButton></header>
  <nav class="task-views" aria-label="Task views"><button v-for="item in views" :key="item" :class="{ active: view === item }" @click="view = item">{{ label(item) }}</button></nav>
  <section class="task-filters" aria-label="Task filters"><select v-model="filters.moduleEnrolmentId"><option value="">All modules</option><option v-for="module in modules" :key="module.enrolmentId || module.id" :value="module.enrolmentId || module.id">{{ module.code || module.module?.code }}</option></select><select v-model="filters.type"><option value="">All types</option><option v-for="item in TASK_TYPES" :key="item">{{ item }}</option></select><select v-model="filters.priority"><option value="">All priorities</option><option v-for="item in TASK_PRIORITIES" :key="item">{{ item }}</option></select><select v-model="filters.status"><option value="">All statuses</option><option v-for="item in TASK_STATUSES" :key="item">{{ item }}</option></select></section>
  <p v-if="error" class="module-alert" role="alert">{{ error }}</p><p v-if="loading" role="status">Loading tasks…</p><p v-else-if="!tasks.length" class="dossier-empty">No tasks in this view.</p>
  <section v-else class="task-list"><article v-for="task in tasks" :key="task.id" class="task-card"><div class="task-card__main"><div><p>{{ task.moduleEnrolment?.offering?.module?.code || 'General' }} · {{ label(task.type) }}</p><h2>{{ task.title }}</h2><span v-if="task.assessment">Assessment: {{ task.assessment.name }}<template v-if="task.assessment.weight !== null"> · {{ task.assessment.weight }}%</template></span><span v-else-if="task.recurringCourseworkOccurrence">{{ task.recurringCoursework?.title }} · {{ task.recurringCourseworkOccurrence.teachingWeek ? `Week ${task.recurringCourseworkOccurrence.teachingWeek}` : `Occurrence ${task.recurringCourseworkOccurrence.sequenceNumber}` }}</span><span>{{ task.dueAt ? new Date(task.dueAt).toLocaleString() : task.timingNote || 'No date set' }} · {{ task.estimatedMinutes ? `${task.estimatedMinutes} min` : 'No estimate' }}</span><span v-if="localMinutes(task)">Recorded on this device: {{ localMinutes(task) }} min</span><span v-if="task.subtaskProgress.total">Subtasks: {{ task.subtaskProgress.completed }} of {{ task.subtaskProgress.total }}</span></div><div><UBadge color="neutral">{{ label(task.priority) }}</UBadge><UBadge color="neutral" variant="outline">{{ label(task.status) }}</UBadge></div></div><div class="task-actions"><UButton v-if="task.status !== 'IN_PROGRESS' && task.status !== 'COMPLETED'" size="sm" variant="outline" @click="start(task)">Start</UButton><UButton size="sm" @click="toggleComplete(task)">{{ task.status === 'COMPLETED' ? 'Reopen' : 'Complete' }}</UButton><UButton size="sm" variant="ghost" @click="navigateTo(plannerRouteForTask(task))">Plan</UButton><UButton size="sm" variant="ghost" @click="navigateTo(focusRouteForTask(task))">Start Focus</UButton><UButton size="sm" variant="ghost" @click="reschedule(task)">Reschedule</UButton><UButton size="sm" variant="ghost" @click="openEdit(task)">Edit</UButton><UButton size="sm" variant="ghost" @click="split(task)">Split</UButton><UButton size="sm" variant="ghost" @click="update(task.id, { status: 'BACKLOG', dueAt: null })">Backlog</UButton><UButton size="sm" variant="ghost" @click="cancel(task)">Cancel</UButton><UButton size="sm" color="error" variant="ghost" @click="destroy(task)">Delete</UButton></div><ul v-if="task.subtasks.length" class="task-subtasks"><li v-for="subtask in task.subtasks" :key="subtask.id"><button @click="toggleComplete(subtask)"><UIcon :name="subtask.status === 'COMPLETED' ? 'i-lucide-circle-check' : 'i-lucide-circle'" /></button><span>{{ subtask.title }}</span></li></ul></article></section>
  <UModal v-model:open="editorOpen" :title="editingId ? 'Edit task' : 'Add task'" description="Connect this action to academic context when useful."><template #body><form id="task-form" class="task-form" @submit.prevent="save"><label>Title<UInput v-model="form.title" required maxlength="240" /><small>{{ fieldErrors.title }}</small></label><div><label>Module<select v-model="form.moduleEnrolmentId"><option value="">General</option><option v-for="module in modules" :key="module.enrolmentId || module.id" :value="module.enrolmentId || module.id">{{ module.code || module.module?.code }}</option></select></label><label>Assessment<select v-model="form.assessmentId"><option value="">None</option><option v-for="item in assessments" :key="item.id" :value="item.id">{{ item.name }}</option></select></label></div><div><label>Type<select v-model="form.type"><option v-for="item in TASK_TYPES" :key="item">{{ item }}</option></select></label><label>Priority<select v-model="form.priority"><option v-for="item in TASK_PRIORITIES" :key="item">{{ item }}</option></select></label></div><div><label>Due date/time<input v-model="form.dueAt" type="datetime-local"></label><label>Estimated minutes<UInput v-model.number="form.estimatedMinutes" type="number" min="0" /></label></div><label>Timing note<UInput v-model="form.timingNote" maxlength="500" placeholder="Before Week 8 quiz" /></label><label>Actual minutes<UInput v-model.number="form.actualMinutes" type="number" min="0" /></label><label>Description<UTextarea v-model="form.description" :rows="4" maxlength="5000" /></label></form></template><template #footer><UButton variant="outline" @click="editorOpen = false">Cancel</UButton><UButton type="submit" form="task-form" :loading="saving">Save task</UButton></template></UModal>
</main></template>
